name: "Code Maintainability Reporter Action"
description: "Reports code complexity & maintainability metrics and differences in pull requests as comments"
author: "Neural Group Inc."
inputs:
  includes:
    description: |
      'List of files to include in the analysis as a comma-separated string.'
      "Example: 'dir1/**/*.py,dir2/**/*.{ts,tsx,js,jsx}'"
    required: true
  excludes:
    description: |
      "List of files to exclude from the analysis as a comma-separated string. "
      "Example: 'dir1/**/test_*.py,dir2/**/*test.{ts,tsx,js,jsx}'"
    default: ''
outputs:
  results_json:
    description: 'Code analysis results in json format.'
runs:
  using: "composite"
  steps:
    # TODO: register the docker image in Dockerhub
    - name: Check out the analyzer repository
      shell: bash
      run: |
        git clone https://github.com/neural-group/code-maintainability-reporter-action.git -b main
    # TODO: register the docker image in Dockerhub
    - name: Build Docker container
      working-directory: code-maintainability-reporter-action
      shell: bash
      run: |
        docker build -t code-maintainability-reporter .

    - name: Check out the repository (head)
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: head-repo

    - name: Run complexity on head branch
      id: analysis_old
      shell: bash
      run: |
        {
          echo 'results<<EOF'
          docker run --rm -v ./head-repo:/target code-maintainability-reporter /target/${{ inputs.includes }} /target/${{ inputs.excludes }}
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Check out the repository (base)
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: base-repo

    - name: Run complexity on base branch
      id: analysis_new
      shell: bash
      run: |
        {
          echo 'results<<EOF'
          docker run --rm -v ./base-repo:/target code-maintainability-reporter /target/${{ inputs.includes }} /target/${{ inputs.excludes }}
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Get code complexity diff
      id: calc_diff
      shell: bash
      run: |
        {
          echo 'results<<EOF'
          docker run --rm code-maintainability-reporter --diff "${{ steps.analysis_old.outputs.results }}" "${{ steps.analysis_new.outputs.results }}"
          echo EOF
        } >> "$GITHUB_OUTPUT"
      continue-on-error: true

    - name: Create a PR comment with the complexity difference
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: | 
          <details>
          <summary>Code Complexity Analytics</summary>

          ${{ steps.calc_diff.outputs.results }}

          </details>
    - name: Clean up
      shell: bash
      run: |
        docker image rm code-maintainability-reporter
        rm -rf code-maintainability-reporter-action target-repo
branding:
  icon: "git-pull-request"
  color: "blue"
